### PR TITLE
Login problems #5 fix

### LINKED ISSUE #5: Login problems
- [ ] There is no Sign-in/Login screen (This is not supposed to be from this module but it will be convenient to add it at this point)
- [ ] There are differences between [The Edit Screen](https://github.com/BluePuppy21/RentAHouse.com/blob/master/Design/Bread%20Scenes/Users/Editprofile.png) and [The Add Screen](https://github.com/BluePuppy21/RentAHouse.com/blob/master/Design/Bread%20Scenes/Users/Signup.png)
- [ ] The [Delete Screen](https://github.com/BluePuppy21/RentAHouse.com/blob/master/Design/Bread%20Scenes/Users/Delete.png) does not need the password field
- [ ] Is the user supposed to be allowed to add a picture? if so, how will he/she/it do it?

### PR DESCRIPTION
**Pull request by BluePuppy21**
I changed another two house pages because of the impact of the edit user and add user screen but that's it

### CODE REVIEW

**Review by obed-vazquez — CHANGES_REQUESTED** [review]
- So I get from here that we are not allowing the user to add a Profile Picture correct? (this sounds like the best option here)

- We might want to bring the same notes that are being added in [RAH-12](https://bluepuppy.atlassian.net/browse/RAH-12?atlOrigin=eyJpIjoiOTFmYzE5YTRkMGJiNDllZmFlMDhlNmYyNmQ5N2M3NDUiLCJwIjoiaiJ9) to here but we must wait until both issues are released. I'll help you configure this.

- It sounds perfect, the User edit screen usually asks for password confirmation but this shouldn't be our focus here.

- **But the same pattern should be reflected on the Delete View and I don't see those changes**.

**Review by obed-vazquez — CHANGES_REQUESTED** [review]
Add house and Edit House views are not supposed to be edited on this issue, The Add and Edit view mentioned in the task description was meant to be the USER Add and Edit views. Create a separate issue for these 2.

**Review by obed-vazquez — CHANGES_REQUESTED** [review]
Please stick to images when adding new mockups, and name them according to the problem you are trying to solve (usually the BREAD specifications, but not this time, they are login)

**Comment by BluePuppy21** [comment]
There are too many problems in this branch and we decided that it was easier and faster to close this branch and generate new one from `master` called `RAH-12-add-house-prototype`.

**Pull request closed without merging**
